name: Test project
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v4

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod

    - name: Install dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Show Codecov link
      run: |
        echo "Coverage report (Codecov): https://app.codecov.io/gh/${{ github.repository }}"

  build-image:
    runs-on: ubuntu-latest
    needs: run-tests
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
