name: Test project
on:
  push:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v4
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
    - name: Install dependencies
      run: go mod download
    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v5
      with:
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Show Codecov link
      run: |
        echo "Coverage report (Codecov): https://app.codecov.io/gh/${{ github.repository }}"
